import os


os.environ.setdefault("STRIPE_PUBLIC_KEY", "pk_test_51JB11CI8PhxHVUmIOfeFKfzS3v2qZxwbhS3N9CWtr4NVg2GBpniLMdCl4zeCG6c1jGTH99VJkFOvvWyLQy0XlBlP00qwPt0yNs"),
os.environ.setdefault("STRIPE_SECRET_KEY", "sk_test_51JB11CI8PhxHVUmIhX8RmuMhAkCpG5AfMKmoL3HbXm3ALQGbskOfRwqPiFByvT61rxOLSV3gj59COweZx4xFPAbT00E7owphdV")
os.environ.setdefault("STRIPE_SECRET_KEY", "STRIPE_PUBLIC_KEY")